<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\SevenRecord.Audio.Windows\SevenRecord.Audio.Windows.csproj" />
    <ProjectReference Include="..\..\src\SevenRecord.Capture.Abstractions\SevenRecord.Capture.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\SevenRecord.Analysis\SevenRecord.Analysis.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-$([System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture.ToString().ToLowerInvariant())</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
